# Generated by Django 6.0.2 on 2026-02-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('JOURNALIST', 'Journalist'), ('READER', 'Reader')], default='READER', max_length=20),
        ),
    ]
