# Generated by Django 6.0.2 on 2026-02-12 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link', models.URLField()),
                ('placement', models.CharField(choices=[('header', 'Header'), ('sidebar', 'Sidebar'), ('article', 'Article'), ('footer', 'Footer')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('target_page', models.CharField(default='all', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SidebarBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('block_type', models.CharField(choices=[('ad', 'Advertisement'), ('trending', 'Trending News'), ('html', 'Custom HTML'), ('category_list', 'Category List')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('target_page', models.CharField(default='all', max_length=50)),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.advertisement')),
            ],
        ),
    ]
