# Generated by Django 6.0.2 on 2026-03-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_advertisement_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebarblock',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='sidebarblock',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='sidebarblock',
            name='target_page',
        ),
        migrations.AddField(
            model_name='sidebarblock',
            name='content',
            field=models.TextField(blank=True, help_text='Used for Custom HTML or Text blocks'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='placement',
            field=models.CharField(choices=[('header', 'Header Banner'), ('sidebar', 'Sidebar Card'), ('article', 'Inline Article'), ('footer', 'Footer Wide')], default='sidebar', max_length=20),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sidebarblock',
            name='block_type',
            field=models.CharField(choices=[('trending', 'Trending News'), ('newsletter', 'Newsletter Subscription'), ('social', 'Social Media Links'), ('html', 'Custom HTML/Text'), ('categories', 'Category List')], default='html', max_length=20),
        ),
        migrations.AlterField(
            model_name='sidebarblock',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
    ]
