# Generated by Django 6.0.2 on 2026-03-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_sidebarblock_options_remove_sidebarblock_ad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebarblock',
            name='block_type',
            field=models.CharField(choices=[('ad', 'Advertisement'), ('html', 'Custom HTML'), ('trending', 'Trending Articles'), ('recommended', 'Recommended For You')], default='html', max_length=20),
        ),
    ]
