# Generated by Django 6.0.2 on 2026-03-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
