# Generated by Django 6.0.2 on 2026-03-14 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_views', to='news.article')),
            ],
            options={
                'indexes': [models.Index(fields=['article', 'ip_address'], name='news_articl_article_a7509c_idx')],
            },
        ),
    ]
