# Generated by Django 6.0.2 on 2026-03-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_articleview'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleview',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
