# Generated by Django 6.0.2 on 2026-03-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_articleview_user_agent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='articleview',
            name='news_articl_article_a7509c_idx',
        ),
        migrations.AddIndex(
            model_name='articleview',
            index=models.Index(fields=['article', 'ip_address', 'user_agent'], name='news_articl_article_0eec67_idx'),
        ),
    ]
