# Generated by Django 6.0.2 on 2026-02-05 16:08

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("Users.user",),
            managers=[
                ("patient", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
